// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PhoneInfo.proto

package exercise;

/**
 * Protobuf type {@code PhoneBook}
 */
public final class PhoneBook extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PhoneBook)
    PhoneBookOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PhoneBook.newBuilder() to construct.
  private PhoneBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PhoneBook() {
    phoneInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PhoneBook();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PhoneBook(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              phoneInfo_ = new java.util.ArrayList<exercise.Phone>();
              mutable_bitField0_ |= 0x00000001;
            }
            phoneInfo_.add(
                input.readMessage(exercise.Phone.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        phoneInfo_ = java.util.Collections.unmodifiableList(phoneInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return exercise.PhoneBookInfo.internal_static_PhoneBook_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return exercise.PhoneBookInfo.internal_static_PhoneBook_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            exercise.PhoneBook.class, exercise.PhoneBook.Builder.class);
  }

  public static final int PHONEINFO_FIELD_NUMBER = 1;
  private java.util.List<exercise.Phone> phoneInfo_;
  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  @java.lang.Override
  public java.util.List<exercise.Phone> getPhoneInfoList() {
    return phoneInfo_;
  }
  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends exercise.PhoneOrBuilder> 
      getPhoneInfoOrBuilderList() {
    return phoneInfo_;
  }
  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  @java.lang.Override
  public int getPhoneInfoCount() {
    return phoneInfo_.size();
  }
  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  @java.lang.Override
  public exercise.Phone getPhoneInfo(int index) {
    return phoneInfo_.get(index);
  }
  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  @java.lang.Override
  public exercise.PhoneOrBuilder getPhoneInfoOrBuilder(
      int index) {
    return phoneInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < phoneInfo_.size(); i++) {
      output.writeMessage(1, phoneInfo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < phoneInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, phoneInfo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof exercise.PhoneBook)) {
      return super.equals(obj);
    }
    exercise.PhoneBook other = (exercise.PhoneBook) obj;

    if (!getPhoneInfoList()
        .equals(other.getPhoneInfoList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPhoneInfoCount() > 0) {
      hash = (37 * hash) + PHONEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static exercise.PhoneBook parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static exercise.PhoneBook parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static exercise.PhoneBook parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static exercise.PhoneBook parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static exercise.PhoneBook parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static exercise.PhoneBook parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static exercise.PhoneBook parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static exercise.PhoneBook parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static exercise.PhoneBook parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static exercise.PhoneBook parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static exercise.PhoneBook parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static exercise.PhoneBook parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(exercise.PhoneBook prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PhoneBook}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PhoneBook)
      exercise.PhoneBookOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return exercise.PhoneBookInfo.internal_static_PhoneBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return exercise.PhoneBookInfo.internal_static_PhoneBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              exercise.PhoneBook.class, exercise.PhoneBook.Builder.class);
    }

    // Construct using exercise.PhoneBook.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPhoneInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (phoneInfoBuilder_ == null) {
        phoneInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        phoneInfoBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return exercise.PhoneBookInfo.internal_static_PhoneBook_descriptor;
    }

    @java.lang.Override
    public exercise.PhoneBook getDefaultInstanceForType() {
      return exercise.PhoneBook.getDefaultInstance();
    }

    @java.lang.Override
    public exercise.PhoneBook build() {
      exercise.PhoneBook result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public exercise.PhoneBook buildPartial() {
      exercise.PhoneBook result = new exercise.PhoneBook(this);
      int from_bitField0_ = bitField0_;
      if (phoneInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          phoneInfo_ = java.util.Collections.unmodifiableList(phoneInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.phoneInfo_ = phoneInfo_;
      } else {
        result.phoneInfo_ = phoneInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof exercise.PhoneBook) {
        return mergeFrom((exercise.PhoneBook)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(exercise.PhoneBook other) {
      if (other == exercise.PhoneBook.getDefaultInstance()) return this;
      if (phoneInfoBuilder_ == null) {
        if (!other.phoneInfo_.isEmpty()) {
          if (phoneInfo_.isEmpty()) {
            phoneInfo_ = other.phoneInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePhoneInfoIsMutable();
            phoneInfo_.addAll(other.phoneInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.phoneInfo_.isEmpty()) {
          if (phoneInfoBuilder_.isEmpty()) {
            phoneInfoBuilder_.dispose();
            phoneInfoBuilder_ = null;
            phoneInfo_ = other.phoneInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            phoneInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhoneInfoFieldBuilder() : null;
          } else {
            phoneInfoBuilder_.addAllMessages(other.phoneInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      exercise.PhoneBook parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (exercise.PhoneBook) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<exercise.Phone> phoneInfo_ =
      java.util.Collections.emptyList();
    private void ensurePhoneInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        phoneInfo_ = new java.util.ArrayList<exercise.Phone>(phoneInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        exercise.Phone, exercise.Phone.Builder, exercise.PhoneOrBuilder> phoneInfoBuilder_;

    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public java.util.List<exercise.Phone> getPhoneInfoList() {
      if (phoneInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phoneInfo_);
      } else {
        return phoneInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public int getPhoneInfoCount() {
      if (phoneInfoBuilder_ == null) {
        return phoneInfo_.size();
      } else {
        return phoneInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public exercise.Phone getPhoneInfo(int index) {
      if (phoneInfoBuilder_ == null) {
        return phoneInfo_.get(index);
      } else {
        return phoneInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public Builder setPhoneInfo(
        int index, exercise.Phone value) {
      if (phoneInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneInfoIsMutable();
        phoneInfo_.set(index, value);
        onChanged();
      } else {
        phoneInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public Builder setPhoneInfo(
        int index, exercise.Phone.Builder builderForValue) {
      if (phoneInfoBuilder_ == null) {
        ensurePhoneInfoIsMutable();
        phoneInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        phoneInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public Builder addPhoneInfo(exercise.Phone value) {
      if (phoneInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneInfoIsMutable();
        phoneInfo_.add(value);
        onChanged();
      } else {
        phoneInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public Builder addPhoneInfo(
        int index, exercise.Phone value) {
      if (phoneInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneInfoIsMutable();
        phoneInfo_.add(index, value);
        onChanged();
      } else {
        phoneInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public Builder addPhoneInfo(
        exercise.Phone.Builder builderForValue) {
      if (phoneInfoBuilder_ == null) {
        ensurePhoneInfoIsMutable();
        phoneInfo_.add(builderForValue.build());
        onChanged();
      } else {
        phoneInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public Builder addPhoneInfo(
        int index, exercise.Phone.Builder builderForValue) {
      if (phoneInfoBuilder_ == null) {
        ensurePhoneInfoIsMutable();
        phoneInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        phoneInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public Builder addAllPhoneInfo(
        java.lang.Iterable<? extends exercise.Phone> values) {
      if (phoneInfoBuilder_ == null) {
        ensurePhoneInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneInfo_);
        onChanged();
      } else {
        phoneInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public Builder clearPhoneInfo() {
      if (phoneInfoBuilder_ == null) {
        phoneInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        phoneInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public Builder removePhoneInfo(int index) {
      if (phoneInfoBuilder_ == null) {
        ensurePhoneInfoIsMutable();
        phoneInfo_.remove(index);
        onChanged();
      } else {
        phoneInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public exercise.Phone.Builder getPhoneInfoBuilder(
        int index) {
      return getPhoneInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public exercise.PhoneOrBuilder getPhoneInfoOrBuilder(
        int index) {
      if (phoneInfoBuilder_ == null) {
        return phoneInfo_.get(index);  } else {
        return phoneInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public java.util.List<? extends exercise.PhoneOrBuilder> 
         getPhoneInfoOrBuilderList() {
      if (phoneInfoBuilder_ != null) {
        return phoneInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phoneInfo_);
      }
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public exercise.Phone.Builder addPhoneInfoBuilder() {
      return getPhoneInfoFieldBuilder().addBuilder(
          exercise.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public exercise.Phone.Builder addPhoneInfoBuilder(
        int index) {
      return getPhoneInfoFieldBuilder().addBuilder(
          index, exercise.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .Phone phoneInfo = 1;</code>
     */
    public java.util.List<exercise.Phone.Builder> 
         getPhoneInfoBuilderList() {
      return getPhoneInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        exercise.Phone, exercise.Phone.Builder, exercise.PhoneOrBuilder> 
        getPhoneInfoFieldBuilder() {
      if (phoneInfoBuilder_ == null) {
        phoneInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            exercise.Phone, exercise.Phone.Builder, exercise.PhoneOrBuilder>(
                phoneInfo_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        phoneInfo_ = null;
      }
      return phoneInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PhoneBook)
  }

  // @@protoc_insertion_point(class_scope:PhoneBook)
  private static final exercise.PhoneBook DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new exercise.PhoneBook();
  }

  public static exercise.PhoneBook getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<PhoneBook>
      PARSER = new com.google.protobuf.AbstractParser<PhoneBook>() {
    @java.lang.Override
    public PhoneBook parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PhoneBook(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PhoneBook> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PhoneBook> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public exercise.PhoneBook getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

