// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PhoneInfo.proto

package exercise;

public interface PhoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Phone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int64 phoneNumber = 2;</code>
   * @return Whether the phoneNumber field is set.
   */
  boolean hasPhoneNumber();
  /**
   * <code>optional int64 phoneNumber = 2;</code>
   * @return The phoneNumber.
   */
  long getPhoneNumber();

  /**
   * <code>optional string address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
