// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PhoneInfo.proto

package exercise;

public interface PhoneBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PhoneBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  java.util.List<exercise.Phone> 
      getPhoneInfoList();
  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  exercise.Phone getPhoneInfo(int index);
  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  int getPhoneInfoCount();
  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  java.util.List<? extends exercise.PhoneOrBuilder> 
      getPhoneInfoOrBuilderList();
  /**
   * <code>repeated .Phone phoneInfo = 1;</code>
   */
  exercise.PhoneOrBuilder getPhoneInfoOrBuilder(
      int index);
}
